// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import localFont from "next/font/local";
// const Futura = localFont({
//   src: [
//     {
//       path: "../public/font/futur.ttf",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "../public/font/Futura Bold font.ttf",
//       weight: "900",
//       style: "bold",
//     },
//     {
//       path: "../public/font/Futura Light font.ttf",
//       weight: "300",
//       style: "light",
//     },
//     {
//       path: "../public/font/futura medium bt.ttf",
//       weight: "600",
//       style: "medium",
//     },
//   ],
//   variable: "--font-futura",
//   display: "swap",
// });
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${Futura.variable} antialiased`}>{children}</body>
//     </html>
//   );
// }

import { Lato } from "next/font/google";
import "./globals.css";
import Footer from "../components/layout/footer";
import ReduxProvider from "@/lib/redux/ReduxProvider";
import { Toaster } from "react-hot-toast";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import HeaderWrapper from "@/components/layout/HeaderWrapper";
// import GetConnected from "@/components/home/GetConnected";

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-futura", // same variable rakhi hai taake existing font-futura classes work karen
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
        <ReduxProvider>
          <HeaderWrapper />
          <ToastContainer position="top-right" autoClose={3000} />
          {children}
          {/* <GetConnected /> */}
          <Toaster position="top-right" reverseOrder={false} />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
